site_name: NodeJS Demo
docs_dir: docs
plugings:
  - techdocs-core

nav:
  - Overview:
    - What is NodeJS Demo: 'index.md'
  - Installation and Configuration:
    - Getting started: 'getting-started.md'
